# Generated by Django 3.2.4 on 2021-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('mail', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(upload_to='ocr/%Y/%m/%d')),
                ('file_extension', models.CharField(blank=True, max_length=250)),
                ('rec_lang', models.CharField(blank=True, choices=[('eng', 'English'), ('rus', 'Русский'), ('fra', 'Francais'), ('ukr', 'Ukrainian'), ('spa', 'Spanish'), ('ita', 'Italian'), ('por', 'Portugese'), ('afr', 'African'), ('chi_tra+chi_sim', 'Chinese')], default='eng', max_length=20)),
                ('ocr_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
