# Generated by Django 3.0.7 on 2020-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(upload_to='ocr/%Y/%m/%d')),
                ('file_extension', models.CharField(blank=True, max_length=250)),
                ('rec_lang', models.CharField(blank=True, choices=[('eng', 'English'), ('rus', 'Russian')], default='eng', max_length=3)),
                ('ocr_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
