# Generated by Django 3.2.4 on 2021-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='rec_lang',
            field=models.CharField(blank=True, choices=[('eng', 'English'), ('rus', 'Русский'), ('fra', 'Francais'), ('ukr', 'Ukrainian'), ('spa', 'Spanish'), ('ita', 'Italian'), ('por', 'Portugese'), ('afr', 'African'), ('chi_tra+chi_sim', 'Chinese')], default='eng', max_length=20),
        ),
    ]
